name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  build_and_push:
    name: Nag
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
    
      - uses: whoan/docker-build-with-cache-action@v5
        with:
          image_name: nag
          username: askannz
          password: ${{ secrets.DOCKERHUB_TOKEN }}

